spring:
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:dao/*.xml
    - classpath:mapperxml/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: fance-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer ' #JWT负载中拿到开头
knife4j:
  #  markdowns: classpath:markdown/*
  basic:
    enable: false
    username: zhangsan
    password: 123456

secure:
  ignored:
    urls: #安全路径白名单
      - /sub/**
      - /doc.html
      - /**/v2/api-docs-ext
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /api/v1/access/**
      - /admin/register



market:
  threadpoolsize: 5
  maxbinds: 5
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.shanghaizhida.finanace: debug
#  file: demo_log.log #配置日志生成路径
server:
  port: 9090
#  path: /var/logs #配置日志文件名称