spring:
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  datasource:
    url: jdbc:mysql://localhost:3306/studentmanager?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.kaiyu: debug
#  file: demo_log.log #配置日志生成路径
server:
  port: 9090
#  path: /var/logs #配置日志文件名称